name: Build Polkadex App (Alpha)

pull_request:
  types: [assigned]

jobs:
  build:
    name: Build Polkadex App for Android and iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Run Tests
        run: flutter test
      - name: Build Android App
        run: flutter build apk
      - name: Build iOS App
        run: flutter build ios --no-codesign
      - name: Upload .apk and .ipa to artifacts
      - uses: actions/upload-artifact@v2
          with:
            name: app-builds
            path: |
              build/app/outputs/apk/release/*.apk
              build/ios/ipa/*.ipa